// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPZ0v5HO08_VBL2XjCprcZjAB_RZGYM28',
    appId: '1:400870823590:web:19244b5dc0092a7aebc667',
    messagingSenderId: '400870823590',
    projectId: 'questionbank-68538',
    authDomain: 'questionbank-68538.firebaseapp.com',
    storageBucket: 'questionbank-68538.firebasestorage.app',
    measurementId: 'G-98JY04E776',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPZ0v5HO08_VBL2XjCprcZjAB_RZGYM28',
    appId: '1:400870823590:web:19244b5dc0092a7aebc667',
    messagingSenderId: '400870823590',
    projectId: 'questionbank-68538',
    authDomain: 'questionbank-68538.firebaseapp.com',
    storageBucket: 'questionbank-68538.firebasestorage.app',
    measurementId: 'G-98JY04E776',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7KM6qEqL78OZGZokGF4xUwgPD42xR9ak',
    appId: '1:400870823590:ios:84955f01c6b94699ebc667',
    messagingSenderId: '400870823590',
    projectId: 'questionbank-68538',
    storageBucket: 'questionbank-68538.firebasestorage.app',
    iosBundleId: 'com.example.questionBank',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7KM6qEqL78OZGZokGF4xUwgPD42xR9ak',
    appId: '1:400870823590:ios:84955f01c6b94699ebc667',
    messagingSenderId: '400870823590',
    projectId: 'questionbank-68538',
    storageBucket: 'questionbank-68538.firebasestorage.app',
    iosBundleId: 'com.example.questionBank',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpADym0Lj4_aqvDVX8NVVxc4SPkR3c9A',
    appId: '1:400870823590:android:d89a3011e5b36c4debc667',
    messagingSenderId: '400870823590',
    projectId: 'questionbank-68538',
    storageBucket: 'questionbank-68538.firebasestorage.app',
  );

}